---
- name: Update all installed packages
  yum:
    name: '*'
    update_cache: yes
    state: latest
- name: Setup EPEL repository
  yum:
    name: epel-release
    state: present
- name: Install required packages
  yum:
    name: '{{ item }}'
    #update_cache: yes
    state: present
  with_items: '{{ centos_pkg }}'
- name: Create pyconjp group
  group:
    name: '{{ pycongrp }}'
- name: Create pyconjp user
  user:
    name: '{{ pyconusr }}'
    group: '{{ pycongrp }}'
    home: '{{ deploydest }}'
    createhome: yes
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
